server:
  port: 8081

adapters:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    virtualhost: "/"
    queue:
      email: "email.events.general"

aws:
  region: us-east-1